apiVersion: v1
kind: Secret
metadata:
  name: avp-sdhub-secret
  annotations:
    avp.kubernetes.io/path: "essential-services/data/custodian"
type: Opaque
stringData:
  ClientID: <clientId>
  ClientSecret: <clientSecret>

