#################################################################################
# Copyright (c) 2022,2023 T-Systems International GmbH
# Copyright (c) 2022,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

ingress:
  enabled: true
  className: "nginx"
  issuer: "letsencrypt-prod"
  domain: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      if ($http_origin ~* "http.?:\/\/(.*\.)?(localhost:3000|catena-x\.net|example\.com|idses-fe\.demo\.catena-x\.net).*$") {
        set $allow_origin $http_origin;
      }

      add_header "Access-Control-Allow-Origin" "$http_origin" always;
      add_header "Access-Control-Allow-Methods" "GET, PUT, POST, OPTIONS, DELETE" always;
      add_header "Access-Control-Allow-Headers" "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization" always;
      add_header "Access-Control-Expose-Headers" "Content-Range";

      if ($request_method = 'OPTIONS') {
        add_header "Access-Control-Allow-Origin" "$http_origin" always;
        add_header "Access-Control-Allow-Methods" "GET, PUT, POST, OPTIONS, DELETE" always;
        add_header "Access-Control-Allow-Headers" "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization" always;
        add_header "Access-Control-Max-Age" "1728000" always;
        add_header "Content-Type" "text/plain charset=UTF-8";
        add_header "Content-Length" 0;
        return 204;
      }
      
  hosts:
    - host: "sdfactory.dev.demo.catena-x.net"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - tlsName: sdfactory.dev.demo.catena-x.net-tls
      hosts:
        - sdfactory.dev.demo.catena-x.net

  
sdfactory:
  secret:
    jwkSetUri: "<path:essential-services/data/custodian-dev#jwkSetUri>"
    clientId: "<path:essential-services/data/custodian-dev#clientId>"
    clientSecret: "<path:essential-services/data/custodian-dev#clientSecret>"
    authServerUrl: "<path:essential-services/data/custodian-dev#auth-server-url>"
    realm: "<path:essential-services/data/custodian-dev#realm>"
    resource: "<path:essential-services/data/custodian-dev#resource>"
    custodianWalletUri: "<path:essential-services/data/custodian-dev#uri>"
    clearingHouseUri: "<path:essential-services/data/custodian-dev#clearingHouse-uri>"
    clearingHouseServerUrl: "<path:essential-services/data/custodian-dev#clearingHouse-serverUrl>"
    clearingHouseRealm: "<path:essential-services/data/custodian-dev#clearingHouse-realm>"
    clearingHouseClientId: "<path:essential-services/data/custodian-dev#clearingHouse-clientId>"
    clearingHouseClientSecret: "<path:essential-services/data/custodian-dev#clearingHouse-clientSecret>"
    verifycredentialsUri: "<path:essential-services/data/custodian-dev#verifiableCredentials-schema2210Url>"
