image: "ghcr.io/catenax-ng/product-sd-hub/sdhub:master"
domain: "sdhub.int.demo.catena-x.net"
name: "sdhub"
portContainer: 8080
portService: 80
replicaCount: 1
issuer: "letsencrypt-prod"
#namespace: product-essential-services
